services:
  - type: web
    name: truefit-backend
    runtime: python
    rootDir: truefit_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    releaseCommand: python manage.py migrate --noinput
    startCommand: gunicorn truefit_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: truefit-db
          property: connectionString
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dade4nctd"
      - key: CLOUDINARY_API_KEY
        value: "187889871374933"
      - key: CLOUDINARY_API_SECRET
        value: "jn9ppWpOmeRSojtiJZ74XiDUFf8"
      - key: SECRET_KEY
        value: "django-insecure-8x9k2m4n6p8q0r2s4t6u8w0y2a4c6e8g0i2k4m6o8q0s2u4w6y8"